citas_admin/blueprints/permisos/views.py
"""
Permisos, vistas
"""
import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message

from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.permisos.forms import PermisoNewWithModuloForm, PermisoNewWithRolForm, PermisoEditForm
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.roles.models import Rol
from citas_admin.blueprints.usuarios.decorators import permission_required

MODULO = "PERMISOS"

permisos = Blueprint("permisos", __name__, template_folder="templates")


@permisos.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@permisos.route("/permisos/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Permisos"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Permiso.query
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "modulo_id" in request.form:
        consulta = consulta.filter_by(modulo_id=request.form["modulo_id"])
    if "rol_id" in request.form:
        consulta = consulta.filter_by(rol_id=request.form["rol_id"])
    registros = consulta.order_by(Permiso.nombre).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": resultado.nombre,
                    "url": url_for("permisos.detail", permiso_id=resultado.id),
                },
                "nivel": resultado.nivel_descrito,
                "modulo": {
                    "nombre": resultado.modulo.nombre,
                    "url": url_for("modulos.detail", modulo_id=resultado.modulo_id) if current_user.can_view("MODULOS") else "",
                },
                "rol": {
                    "nombre": resultado.rol.nombre,
                    "url": url_for("roles.detail", rol_id=resultado.rol_id) if current_user.can_view("ROLES") else "",
                },
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@permisos.route("/permisos")
def list_active():
    """Listado de Permisos activos"""
    return render_template(
        "permisos/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Permisos",
        estatus="A",
    )


@permisos.route("/permisos/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Permisos inactivos"""
    return render_template(
        "permisos/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Permisos inactivos",
        estatus="B",
    )


@permisos.route("/permisos/<int:permiso_id>")
def detail(permiso_id):
    """Detalle de un Permiso"""
    permiso = Permiso.query.get_or_404(permiso_id)
    return render_template("permisos/detail.jinja2", permiso=permiso)


@permisos.route("/permisos/nuevo_con_rol/<int:rol_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new_with_rol(rol_id):
    """Nuevo Permiso con Rol"""
    rol = Rol.query.get_or_404(rol_id)
    form = PermisoNewWithRolForm()
    if form.validate_on_submit():
        modulo = form.modulo.data
        nivel = form.nivel.data
        nombre = f"{rol.nombre} puede {Permiso.NIVELES[nivel]} en {modulo.nombre}"
        if Permiso.query.filter(Permiso.modulo == modulo).filter(Permiso.rol == rol).first() is not None:
            flash(f"CONFLICTO: Ya existe {rol.nombre} en {modulo.nombre}. Mejor recupere el registro.", "warning")
            return redirect(url_for("permisos.list_inactive"))
        permiso = Permiso(
            modulo=modulo,
            rol=rol,
            nombre=nombre,
            nivel=nivel,
        )
        permiso.save()
        flash(safe_message(f"Nuevo permiso {nombre}"), "success")
        return redirect(url_for("roles.detail", rol_id=rol.id))
    form.rol.data = rol.nombre
    return render_template(
        "permisos/new_with_rol.jinja2",
        form=form,
        rol=rol,
        titulo=f"Agregar permiso al rol {rol.nombre}",
    )


@permisos.route("/permisos/nuevo_con_modulo/<int:modulo_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new_with_modulo(modulo_id):
    """Nuevo Permiso con Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    form = PermisoNewWithModuloForm()
    if form.validate_on_submit():
        rol = form.rol.data
        nivel = form.nivel.data
        nombre = f"{rol.nombre} puede {Permiso.NIVELES[nivel]} en {modulo.nombre}"
        if Permiso.query.filter(Permiso.modulo == modulo).filter(Permiso.rol == rol).first() is not None:
            flash(f"CONFLICTO: Ya existe {nombre}. Mejor recupere el registro.", "warning")
            return redirect(url_for("permisos.list_inactive"))
        permiso = Permiso(
            modulo=modulo,
            rol=rol,
            nombre=nombre,
            nivel=nivel,
        )
        permiso.save()
        flash(safe_message(f"Nuevo permiso {nombre}"), "success")
        return redirect(url_for("modulos.detail", modulo_id=modulo.id))
    form.modulo.data = modulo.nombre
    return render_template(
        "permisos/new_with_modulo.jinja2",
        form=form,
        modulo=modulo,
        titulo=f"Agregar permiso al módulo {modulo.nombre}",
    )


@permisos.route("/permisos/edicion/<int:permiso_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(permiso_id):
    """Editar Permiso"""
    permiso = Permiso.query.get_or_404(permiso_id)
    form = PermisoEditForm()
    if form.validate_on_submit():
        permiso.nivel = form.nivel.data
        permiso.nombre = f"{permiso.rol.nombre} puede {Permiso.NIVELES[permiso.nivel]} en {permiso.modulo.nombre}"
        permiso.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Editado permiso {permiso.nombre}"),
            url=url_for("permisos.detail", permiso_id=permiso.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    form.nivel.data = permiso.nivel
    return render_template("permisos/edit.jinja2", form=form, permiso=permiso)


@permisos.route("/permisos/eliminar/<int:permiso_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(permiso_id):
    """Eliminar Permiso"""
    permiso = Permiso.query.get_or_404(permiso_id)
    if permiso.estatus == "A":
        permiso.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado permiso {permiso.nombre}"),
            url=url_for("permisos.detail", permiso_id=permiso.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("permisos.detail", permiso_id=permiso.id))


@permisos.route("/permisos/recuperar/<int:permiso_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(permiso_id):
    """Recuperar Permiso"""
    permiso = Permiso.query.get_or_404(permiso_id)
    if permiso.estatus == "B":
        permiso.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado permiso {permiso.nombre}"),
            url=url_for("permisos.detail", permiso_id=permiso.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("permisos.detail", permiso_id=permiso.id))

citas_admin/blueprints/permisos/templates/permisos/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Permiso{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Permiso ' + permiso.nombre) %}
        {{ topbar.button_previous('Permisos', url_for('permisos.list_active')) }}
        {% if current_user.can_edit('PERMISOS') %}
            {{ topbar.button_edit('Editar', url_for('permisos.edit', permiso_id=permiso.id)) }}
            {% if permiso.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('permisos.delete', permiso_id=permiso.id)) }}{% endif %}
            {% if permiso.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('permisos.recover', permiso_id=permiso.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=permiso.estatus) %}
        {{ detail.label_value('Rol', permiso.rol.nombre, url_for('roles.detail', rol_id=permiso.rol_id)) }}
        {{ detail.label_value('Módulo', permiso.modulo.nombre, url_for('modulos.detail', modulo_id=permiso.modulo_id)) }}
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('PERMISOS') %}
        {% if permiso.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + permiso.nombre + '?') }}{% endif %}
        {% if permiso.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', 'Recuperar a ' + permiso.nombre + '?') }}{% endif %}
    {% endif %}
{% endblock %}

citas_admin/blueprints/permisos/templates/permisos/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Permiso{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar permiso ' + permiso.nombre) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'permiso_id': permiso.id} %}
        {% call f.form_tag('permisos.edit', fid='permiso_form', **form_kwargs) %}
            {% call f.form_group(form.nivel) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/permisos/templates/permisos/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Permisos{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('MODULOS') %}
            {{ topbar.button('Módulos', url_for('modulos.list_active'), 'mdi:toy-brick') }}
        {% endif %}
        {% if current_user.can_view('ROLES') %}
            {{ topbar.button('Roles', url_for('roles.list_active'), 'mdi:gamepad') }}
        {% endif %}
        {% if current_user.can_view('USUARIOS') %}
            {{ topbar.button('Usuarios', url_for('usuarios.list_active'), 'mdi:account-key') }}
        {% endif %}
        {% if current_user.can_edit('PERMISOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('permisos.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('permisos.list_active')) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="permisos_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Rol</th>
                    <th>Módulo</th>
                    <th>Nivel</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/permisos/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: "detalle" },
            { data: "rol" },
            { data: "modulo" },
            { data: "nivel" }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            },
            {
                targets: 1, // rol
                data: null,
                render: function(data, type, row, meta) {
                    if (data.url == '') {
                        return data.nombre;
                    } else {
                        return '<a href="' + data.url + '">' + data.nombre + '</a>';
                    }
                }
            },
            {
                targets: 2, // modulo
                data: null,
                render: function(data, type, row, meta) {
                    if (data.url == '') {
                        return data.nombre;
                    } else {
                        return '<a href="' + data.url + '">' + data.nombre + '</a>';
                    }
                }
            }
        ];
        $('#permisos_datatable').DataTable(configDataTable);
    </script>
{% endblock %}

citas_admin/blueprints/permisos/templates/permisos/new_with_modulo.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Agregar permiso al módulo{% endblock %}

{% block topbar_actions %}
    {{ topbar.page(titulo) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'modulo_id': modulo.id} %}
        {% call f.form_tag('permisos.new_with_modulo', fid='permiso_form', **form_kwargs) %}
            {% call f.form_group(form.modulo, readonly=true) %}{% endcall %}
            {% call f.form_group(form.rol) %}{% endcall %}
            {% call f.form_group(form.nivel) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/permisos/templates/permisos/new_with_rol.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Agregar permiso al rol{% endblock %}

{% block topbar_actions %}
    {{ topbar.page(titulo) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'rol_id': rol.id} %}
        {% call f.form_tag('permisos.new_with_rol', fid='permiso_form', **form_kwargs) %}
            {% call f.form_group(form.modulo, ) %}{% endcall %}
            {% call f.form_group(form.rol, readonly=true) %}{% endcall %}
            {% call f.form_group(form.nivel) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}