citas_admin/blueprints/domicilios/views.py
"""
Domicilios, vistas
"""
import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_string, safe_message

from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.domicilios.forms import DomicilioForm, DomicilioSearchForm
from citas_admin.blueprints.domicilios.models import Domicilio
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.usuarios.decorators import permission_required

MODULO = "DOMICILIOS"

domicilios = Blueprint("domicilios", __name__, template_folder="templates")


@domicilios.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@domicilios.route("/domicilios/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Domicilios"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Domicilio.query
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "estado" in request.form:
        consulta = consulta.filter(Domicilio.estado.contains(safe_string(request.form["estado"])))
    if "municipio" in request.form:
        consulta = consulta.filter(Domicilio.municipio.contains(safe_string(request.form["municipio"])))
    if "calle" in request.form:
        consulta = consulta.filter(Domicilio.calle.contains(safe_string(request.form["calle"])))
    if "colonia" in request.form:
        consulta = consulta.filter(Domicilio.colonia.contains(safe_string(request.form["colonia"])))
    if "cp" in request.form:
        consulta = consulta.filter_by(colonia=int(request.form["cp"]))
    registros = consulta.order_by(Domicilio.id.desc()).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "id": resultado.id,
                    "url": url_for("domicilios.detail", domicilio_id=resultado.id),
                },
                "estado": resultado.estado,
                "municipio": resultado.municipio,
                "calle": resultado.calle,
                "num_ext": resultado.num_ext,
                "num_int": resultado.num_int,
                "colonia": resultado.colonia,
                "cp": resultado.cp,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@domicilios.route("/domicilios")
def list_active():
    """Listado de Modulo activos"""
    return render_template(
        "domicilios/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Domicilios",
        estatus="A",
    )


@domicilios.route("/domicilios/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Domicilios inactivos"""
    return render_template(
        "domicilios/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Domicilios inactivos",
        estatus="B",
    )


@domicilios.route("/domicilios/buscar", methods=["GET", "POST"])
def search():
    """Buscar Domicilios"""
    form_search = DomicilioSearchForm()
    if form_search.validate_on_submit():
        busqueda = {"estatus": "A"}
        titulos = []
        if form_search.estado.data:
            estado = safe_string(form_search.estado.data)
            if estado != "":
                busqueda["estado"] = estado
                titulos.append("estado " + estado)
        if form_search.municipio.data:
            municipio = safe_string(form_search.municipio.data)
            if municipio != "":
                busqueda["municipio"] = municipio
                titulos.append("municipio " + municipio)
        if form_search.calle.data:
            calle = safe_string(form_search.calle.data)
            if calle != "":
                busqueda["calle"] = calle
                titulos.append("calle " + calle)
        if form_search.colonia.data:
            colonia = safe_string(form_search.colonia.data)
            if colonia != "":
                busqueda["colonia"] = colonia
                titulos.append("colonia " + colonia)
        if form_search.cp.data:
            cp = int(form_search.cp.data)
            if cp:
                busqueda["cp"] = cp
                titulos.append("C.P. " + cp)
        return render_template(
            "domicilios/list.jinja2",
            filtros=json.dumps(busqueda),
            titulo="Domicilios con " + ", ".join(titulos),
            estatus="A",
        )
    return render_template("domicilios/search.jinja2", form=form_search)


@domicilios.route("/domicilios/<int:domicilio_id>")
def detail(domicilio_id):
    """Detalle de un Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    return render_template("domicilios/detail.jinja2", domicilio=domicilio)


@domicilios.route("/domicilios/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Domicilio"""
    form = DomicilioForm()
    if form.validate_on_submit():
        estado = safe_string(form.estado.data, max_len=64)
        municipio = safe_string(form.municipio.data, max_len=64)
        calle = safe_string(form.calle.data, max_len=256)
        num_ext = safe_string(form.num_ext.data, max_len=24)
        num_int = safe_string(form.num_int.data, max_len=24)
        colonia = safe_string(form.colonia.data, max_len=256)
        cp = form.cp.data
        completo = f"{calle} #{num_ext} {num_int}, {colonia}, {municipio}, {estado}, C.P. {cp}"
        domicilio = Domicilio(
            estado=estado,
            municipio=municipio,
            calle=calle,
            num_ext=num_ext,
            num_int=num_int,
            colonia=colonia,
            cp=cp,
            completo=completo,
        ).save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Nuevo Domicilio {completo}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return render_template("domicilios/new.jinja2", form=form)


@domicilios.route("/domicilios/edicion/<int:domicilio_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(domicilio_id):
    """Editar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    form = DomicilioForm()
    if form.validate_on_submit():
        domicilio.estado = safe_string(form.estado.data, max_len=64)
        domicilio.municipio = safe_string(form.municipio.data, max_len=64)
        domicilio.calle = safe_string(form.calle.data, max_len=256)
        domicilio.num_ext = safe_string(form.num_ext.data, max_len=24)
        domicilio.num_int = safe_string(form.num_int.data, max_len=24)
        domicilio.colonia = safe_string(form.colonia.data, max_len=256)
        domicilio.cp = form.cp.data
        domicilio.completo = f"{domicilio.calle} #{domicilio.num_ext} {domicilio.num_int}, {domicilio.colonia}, {domicilio.municipio}, {domicilio.estado}, C.P. {domicilio.cp}"
        domicilio.save()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Editado el Domicilio {domicilio.completo}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    form.estado.data = domicilio.estado
    form.municipio.data = domicilio.municipio
    form.calle.data = domicilio.calle
    form.num_ext.data = domicilio.num_ext
    form.num_int.data = domicilio.num_int
    form.colonia.data = domicilio.colonia
    form.cp.data = domicilio.cp
    return render_template("domicilios/edit.jinja2", form=form, domicilio=domicilio)


@domicilios.route("/domicilios/eliminar/<int:domicilio_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(domicilio_id):
    """Eliminar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    if domicilio.estatus == "A":
        domicilio.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado el Domicilio {domicilio.calle}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("domicilios.detail", domicilio_id=domicilio_id))


@domicilios.route("/domicilios/recuperar/<int:domicilio_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(domicilio_id):
    """Recuperar Domicilio"""
    domicilio = Domicilio.query.get_or_404(domicilio_id)
    if domicilio.estatus == "B":
        domicilio.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado el Servicio {domicilio.calle}"),
            url=url_for("domicilios.detail", domicilio_id=domicilio.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("domicilios.detail", domicilio_id=domicilio_id))

citas_admin/blueprints/domicilios/templates/domicilios/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Domicilio{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Domicilio') %}
        {{ topbar.button_previous('Domicilios', url_for('domicilios.list_active')) }}
        {% if current_user.can_edit('DOMICILIOS') %}
            {{ topbar.button_edit('Editar', url_for('domicilios.edit', domicilio_id=domicilio.id)) }}
            {% if domicilio.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('domicilios.delete', domicilio_id=domicilio.id)) }}{% endif %}
            {% if domicilio.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('domicilios.recover', domicilio_id=domicilio.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=domicilio.estatus) %}
        {{ detail.label_value('Calle', domicilio.calle) }}
        {{ detail.label_value('No. Exterior', domicilio.num_ext) }}
        {{ detail.label_value('No. Interior', domicilio.num_int) }}
        {{ detail.label_value('Colonia', domicilio.colonia) }}
        {{ detail.label_value('Municipio', domicilio.municipio) }}
        {{ detail.label_value('Estado', domicilio.estado) }}
        {{ detail.label_value('C.P.', domicilio.cp) }}
    {% endcall %}
    {% if current_user.can_view('OFICINAS') %}
        {% call detail.card('Oficinas') %}
            <table id="oficinas_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Claves</th>
                        <th>Descripciones</th>
                        <th>Distritos</th>
                        <th>Aperturas</th>
                        <th>Cierres</th>
                        <th>L. P.</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('DOMICILIOS') %}
        {% if domicilio.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar el domicilio en la calle: ' + domicilio.calle + '?') }}{% endif %}
        {% if domicilio.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar el domicilio en la calle: ' + domicilio.calle + '?') }}{% endif %}
    {% endif %}
    {{ detail.config_datatable() }}
    {% if current_user.can_view('OFICINAS') %}
        <script>
            configDataTable['ajax']['url'] = '/oficinas/datatable_json';
            configDataTable['ajax']['data'] = { 'estatus': "A", 'domicilio_id': {{ domicilio.id}} };
            configDataTable['columns'] = [
                { data: "detalle" },
                { data: "descripcion_corta" },
                { data: "distrito" },
                { data: "apertura" },
                { data: "cierre" },
                { data: "limite_personas" }
            ];
            configDataTable['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.clave + '</a>';
                    }
                },
                {
                    targets: 1, // descripcion_corta
                    data: null,
                    render: function(data, type, row, meta) {
                        return (data.length > 48 ? data.substr(0, 48) + '…' : data);
                    }
                },
                {
                    targets: 2, // distrito
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.nombre_corto;
                        } else {
                            return '<a href="' + data.url + '">' + data.nombre_corto + '</a>';
                        }
                    }
                }
            ];
            $('#oficinas_datatable').DataTable(configDataTable);
        </script>
    {% endif %}
    {{ detail.moment_js(moment) }}
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Domicilio{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar ' +  domicilio.calle ) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'domicilio_id': domicilio.id} %}
        {% call f.form_tag('domicilios.edit', fid='domicilio_id_form', **form_kwargs) %}
            {% call f.form_group(form.estado) %}{% endcall %}
            {% call f.form_group(form.municipio) %}{% endcall %}
            {% call f.form_group(form.calle) %}{% endcall %}
            {% call f.form_group(form.num_ext) %}{% endcall %}
            {% call f.form_group(form.num_int) %}{% endcall %}
            {% call f.form_group(form.colonia) %}{% endcall %}
            {% call f.form_group(form.cp) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Domicilios{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('OFICINAS') %}
            {{ topbar.button('Oficinas', url_for('oficinas.list_active'), 'mdi:store') }}
        {% endif %}
        {% if current_user.can_edit('DOMICILIOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('domicilios.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('domicilios.list_active')) }}{% endif %}
        {% endif %}
            {{ topbar.button_new('Nuevo Domicilio', url_for('domicilios.new')) }}
        {{ topbar.button_search('Buscar', url_for('domicilios.search')) }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="domicilios_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>IDs</th>
                    <th>Estados</th>
                    <th>Municipios</th>
                    <th>Calles</th>
                    <th>No. Ext.</th>
                    <th>No. Int.</th>
                    <th>Colonias</th>
                    <th>C.P.</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/domicilios/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: "detalle" },
            { data: "estado" },
            { data: "municipio" },
            { data: "calle" },
            { data: "num_ext" },
            { data: "num_int" },
            { data: "colonia" },
            { data: "cp" },
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, //detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.id + '</a>';
                }
            },
            {
                targets: [1, 2, 3, 6], // estado, municipio, calle, colonia
                data: null,
                render: function(data, type, row, meta) {
                    return data.length > 16 ? data.substr(0, 16) + '…' : data;
                }
            }
        ];
        $('#domicilios_datatable').DataTable(configDataTable);
    </script>
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Domicilio{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Domicilio') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('domicilios.new', fid='domicilios_form') %}
            {% call f.form_group(form.estado) %}{% endcall %}
            {% call f.form_group(form.municipio) %}{% endcall %}
            {% call f.form_group(form.calle) %}{% endcall %}
            {% call f.form_group(form.num_ext) %}{% endcall %}
            {% call f.form_group(form.num_int) %}{% endcall %}
            {% call f.form_group(form.colonia) %}{% endcall %}
            {% call f.form_group(form.cp) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/domicilios/templates/domicilios/search.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Buscar Domicilios{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Buscar Domicilios') %}
        {{ topbar.button_previous('Domicilios', url_for('domicilios.list_active')) }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('domicilios.search', fid='domicilios_search_form') %}
            {% call f.form_group(form.estado) %}{% endcall %}
            {% call f.form_group(form.municipio) %}{% endcall %}
            {% call f.form_group(form.calle) %}{% endcall %}
            {% call f.form_group(form.colonia) %}{% endcall %}
            {% call f.form_group(form.cp) %}{% endcall %}
            {{ form.buscar() }}
        {% endcall %}
    {% endcall %}
{% endblock %}