citas_admin/blueprints/modulos/models.py
"""
Modulos, modelos
"""
from citas_admin.extensions import db
from lib.universal_mixin import UniversalMixin


class Modulo(db.Model, UniversalMixin):
    """Modulo"""

    # Nombre de la tabla
    __tablename__ = "modulos"

    # Clave primaria
    id = db.Column(db.Integer, primary_key=True)

    # Columnas
    nombre = db.Column(db.String(256), unique=True, nullable=False)
    nombre_corto = db.Column(db.String(64), nullable=False)
    icono = db.Column(db.String(48), nullable=False)
    ruta = db.Column(db.String(64), nullable=False)
    en_navegacion = db.Column(db.Boolean, nullable=False, default=True)

    # Hijos
    bitacoras = db.relationship("Bitacora", back_populates="modulo")
    permisos = db.relationship("Permiso", back_populates="modulo")

    def __repr__(self):
        """Representación"""
        return f"<Modulo {self.nombre}>"

citas_admin/blueprints/modulos/forms.py
"""
Modulos, formularios
"""
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, SubmitField
from wtforms.validators import DataRequired, Length, Optional


class ModuloForm(FlaskForm):
    """Formulario Modulo"""

    nombre = StringField("Nombre", validators=[DataRequired(), Length(max=256)])
    nombre_corto = StringField("Nombre para menú", validators=[DataRequired(), Length(max=64)])
    icono = StringField("Icono", validators=[DataRequired(), Length(max=48)], default="mdi:folder")
    ruta = StringField("Ruta (comienza con /)", validators=[DataRequired(), Length(max=64)], default="/")
    en_navegacion = BooleanField("En menú de navegación", validators=[Optional()])
    guardar = SubmitField("Guardar")

citas_admin/blueprints/modulos/views.py
"""
Modulos, vistas
"""
import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_message, safe_string

from citas_admin.blueprints.bitacoras.models import Bitacora
from citas_admin.blueprints.modulos.models import Modulo
from citas_admin.blueprints.modulos.forms import ModuloForm
from citas_admin.blueprints.permisos.models import Permiso
from citas_admin.blueprints.usuarios.decorators import permission_required

MODULO = "MODULOS"

modulos = Blueprint("modulos", __name__, template_folder="templates")


@modulos.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@modulos.route("/modulos/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Modulos"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Modulo.query
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    registros = consulta.order_by(Modulo.nombre).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "nombre": resultado.nombre,
                    "url": url_for("modulos.detail", modulo_id=resultado.id),
                },
                "icono": resultado.icono,
                "en_navegacion": resultado.en_navegacion,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@modulos.route("/modulos")
def list_active():
    """Listado de Modulos activos"""
    return render_template(
        "modulos/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Módulos",
        estatus="A",
    )


@modulos.route("/modulos/inactivos")
@permission_required(MODULO, Permiso.MODIFICAR)
def list_inactive():
    """Listado de Modulos inactivos"""
    return render_template(
        "modulos/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Módulos inactivos",
        estatus="B",
    )


@modulos.route("/modulos/<int:modulo_id>")
def detail(modulo_id):
    """Detalle de un Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    return render_template("modulos/detail.jinja2", modulo=modulo)


@modulos.route("/modulos/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Modulo"""
    form = ModuloForm()
    if form.validate_on_submit():
        # Validar que el nombre no se repita
        nombre = safe_string(form.nombre.data)
        if Modulo.query.filter_by(nombre=nombre).first():
            flash("La nombre ya está en uso. Debe de ser único.", "warning")
        else:
            modulo = Modulo(
                nombre=nombre,
                nombre_corto=safe_string(form.nombre_corto.data, to_uppercase=False, do_unidecode=False),
                icono=form.icono.data,
                ruta=form.ruta.data,
                en_navegacion=form.en_navegacion.data == 1,
            )
            modulo.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nuevo módulo {modulo.nombre}"),
                url=url_for("modulos.detail", modulo_id=modulo.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    return render_template("modulos/new.jinja2", form=form)


@modulos.route("/modulos/edicion/<int:modulo_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(modulo_id):
    """Editar Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    form = ModuloForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia el nombre verificar que no este en uso
        nombre = safe_string(form.nombre.data)
        if modulo.nombre != nombre:
            modulo_existente = Modulo.query.filter_by(nombre=nombre).first()
            if modulo_existente and modulo_existente.id != modulo.id:
                es_valido = False
                flash("El nombre ya está en uso. Debe de ser único.", "warning")
        # Si es valido actualizar
        if es_valido:
            modulo.nombre = nombre
            modulo.nombre_corto = safe_string(form.nombre_corto.data, to_uppercase=False, do_unidecode=False)
            modulo.icono = form.icono.data
            modulo.ruta = form.ruta.data
            modulo.en_navegacion = form.en_navegacion.data == 1
            modulo.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado módulo {modulo.nombre}"),
                url=url_for("modulos.detail", modulo_id=modulo.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.nombre.data = modulo.nombre
    form.nombre_corto.data = modulo.nombre_corto
    form.icono.data = modulo.icono
    form.ruta.data = modulo.ruta
    if modulo.en_navegacion:
        form.en_navegacion.data = 1
    else:
        form.en_navegacion.data = 0
    return render_template("modulos/edit.jinja2", form=form, modulo=modulo)


@modulos.route("/modulos/eliminar/<int:modulo_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def delete(modulo_id):
    """Eliminar Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    if modulo.estatus == "A":
        modulo.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado módulo {modulo.nombre}"),
            url=url_for("modulos.detail", modulo_id=modulo.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("modulos.detail", modulo_id=modulo.id))


@modulos.route("/modulos/recuperar/<int:modulo_id>")
@permission_required(MODULO, Permiso.MODIFICAR)
def recover(modulo_id):
    """Recuperar Modulo"""
    modulo = Modulo.query.get_or_404(modulo_id)
    if modulo.estatus == "B":
        modulo.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado módulo {modulo.nombre}"),
            url=url_for("modulos.detail", modulo_id=modulo.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
        return redirect(bitacora.url)
    return redirect(url_for("modulos.detail", modulo_id=modulo.id))

citas_admin/blueprints/modulos/templates/modulos/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Módulo{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Módulo ' + modulo.nombre) %}
        {{ topbar.button_previous('Módulos', url_for('modulos.list_active')) }}
        {% if current_user.can_edit('MODULOS') %}
            {{ topbar.button_edit('Editar', url_for('modulos.edit', modulo_id=modulo.id)) }}
            {% if modulo.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('modulos.delete', modulo_id=modulo.id)) }}{% endif %}
            {% if modulo.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('modulos.recover', modulo_id=modulo.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=modulo.estatus) %}
        {{ detail.label_value('Nombre en menú', modulo.nombre_corto) }}
        {{ detail.label_value('Icono', modulo.icono) }}
        {{ detail.label_value('Ruta', modulo.ruta) }}
        {{ detail.label_value_boolean('En menú de navegación', modulo.en_navegacion) }}
    {% endcall %}
    {% call detail.card('Permisos') %}
        <table id="permisos_datatable" class="table display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Niveles</th>
                    <th>Roles</th>
                </tr>
            </thead>
        </table>
        {% if current_user.can_insert('PERMISOS') %}
        <a href="{{ url_for('permisos.new_with_modulo', modulo_id=modulo.id) }}" class="btn btn-primary">Agregar</a>
        {% endif %}
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_edit('MODULOS') %}
        {% if modulo.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + modulo.nombre + '?') }}{% endif %}
        {% if modulo.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', 'Recuperar a ' + modulo.nombre + '?') }}{% endif %}
    {% endif %}
    {{ modals.custom_javascript('Eliminar', '¿Eliminar ese permiso del rol?', 'DeletePermiso') }}
    {{ detail.config_datatable() }}
    {% if current_user.can_view('PERMISOS') %}
        <script>
            configDataTable['ajax']['url'] = '/permisos/datatable_json';
            configDataTable['ajax']['data'] = { 'estatus': "A", 'modulo_id': {{ modulo.id}} };
            configDataTable['columns'] = [
                { data: "detalle" },
                { data: "rol" }
            ];
            configDataTable['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.nombre + '</a>';
                    }
                },
                {
                    targets: 1, // rol
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.url == '') {
                            return data.nombre;
                        } else {
                            return '<a href="' + data.url + '">' + data.nombre + '</a>';
                        }
                    }
                }
            ];
            $('#permisos_datatable').DataTable(configDataTable);
        </script>
    {% endif %}
{% endblock %}

citas_admin/blueprints/modulos/templates/modulos/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Módulo{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Editar módulo ' + modulo.nombre) }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'modulo_id': modulo.id} %}
        {% call f.form_tag('modulos.edit', fid='modulo_form', **form_kwargs) %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.icono) %}{% endcall %}
            {% call f.form_group(form.ruta) %}{% endcall %}
            {% call f.form_group(form.en_navegacion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

citas_admin/blueprints/modulos/templates/modulos/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Modulos{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('ROLES') %}
            {{ topbar.button('Roles', url_for('roles.list_active'), 'mdi:gamepad') }}
        {% endif %}
        {% if current_user.can_view('USUARIOS') %}
            {{ topbar.button('Usuarios', url_for('usuarios.list_active'), 'mdi:account-key') }}
        {% endif %}
        {% if current_user.can_edit('MODULOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('modulos.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('modulos.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('MODULOS') %}
            {{ topbar.button_new('Nuevo Modulo', url_for('modulos.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="modulos_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Nombres</th>
                    <th>Iconos</th>
                    <th>En menú de navegación</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/modulos/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' },
            { data: 'icono' },
            { data: 'en_navegacion' }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.nombre + '</a>';
                }
            },
            {
                targets: 1, // icono
                data: null,
                render: function(data, type, row, meta) {
                    return '<span class="iconify" data-icon="' + data + '" style="font-size: 1.4em"></span>';
                }
            },
            {
                targets: 2, // en_navegacion
                data: null,
                render: function(data, type, row, meta) {
                    if (data) {
                        return 'SI';
                    }
                    return '';
                }
            }
        ];
        $('#modulos_datatable').DataTable(configDataTable);
    </script>
{% endblock %}

citas_admin/blueprints/modulos/templates/modulos/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Módulo{% endblock %}

{% block topbar_actions %}
    {{ topbar.page('Nuevo Módulo') }}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('modulos.new', fid='modulo_form') %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.icono) %}{% endcall %}
            {% call f.form_group(form.ruta) %}{% endcall %}
            {% call f.form_group(form.en_navegacion) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}